// The app's pictogram set: full-colour glyphs (Noto Emoji, Apache 2.0) so
// they look the same on every device, unlike system emoji. Kept free of React
// Native imports so it runs under `node --test`; the images themselves are in
// ./glyph-sources.ts, generated by scripts/generate-glyphs.mjs from this list.
export const GLYPH_NAMES = [
  // Ingredients
  "coconut",
  "peanuts",
  "chestnut",
  "garlic",
  "onion",
  "tomato",
  "lemon",
  "hot-pepper",
  "bell-pepper",
  "carrot",
  "potato",
  "eggplant",
  "cucumber",
  "leafy-green",
  "broccoli",
  "mushroom",
  "ear-of-corn",
  "avocado",
  "olive",
  "herb",
  "ginger-root",
  "shrimp",
  "fish",
  "poultry-leg",
  "cut-of-meat",
  "egg",
  "butter",
  "cheese-wedge",
  "glass-of-milk",
  "cooked-rice",
  "spaghetti",
  "bread",
  "sheaf-of-rice",
  "beans",
  "honey-pot",
  "candy",
  "salt",
  "palm-tree",
  "red-apple",
  "banana",
  "grapes",
  "chocolate-bar",
  "canned-food",
  "droplet",
  "spoon",
  // Meals and everything else
  "green-salad",
  "shallow-pan-of-food",
  "fork-and-knife-with-plate",
  "mobile-phone",
  "spiral-calendar",
  "money-bag",
  "house",
  "house-with-garden",
  "bust-in-silhouette",
  "busts-in-silhouette",
  "bookmark",
  "alarm-clock",
  "wastebasket",
  "hourglass-done",
  "globe-with-meridians",
  "straight-ruler",
  "bar-chart",
] as const;

export type GlyphName = (typeof GLYPH_NAMES)[number];

// Maps an ingredient name (English or Arabic) to its glyph. First matching
// keyword wins, so more specific entries come before broader ones.
const FOOD_GLYPHS: Array<[glyph: GlyphName, keywords: string[]]> = [
  ["coconut", ["coconut", "جوز الهند"]],
  ["peanuts", ["peanut", "فول سوداني"]],
  ["garlic", ["garlic", "ثوم"]],
  ["onion", ["onion", "shallot", "scallion", "بصل"]],
  ["tomato", ["tomato", "طماطم", "بندورة"]],
  ["lemon", ["lemon", "lime", "ليمون"]],
  ["hot-pepper", ["chili", "chilli", "jalape", "cayenne", "paprika", "فلفل حار", "شطة"]],
  ["bell-pepper", ["bell pepper", "capsicum", "فلفل رومي", "فليفلة"]],
  ["carrot", ["carrot", "جزر"]],
  ["potato", ["potato", "بطاطس", "بطاطا"]],
  ["eggplant", ["eggplant", "aubergine", "باذنجان"]],
  ["cucumber", ["cucumber", "zucchini", "courgette", "خيار", "كوسا"]],
  ["leafy-green", ["kale", "spinach", "lettuce", "cabbage", "greens", "okra", "سبانخ", "خس", "كرنب", "ملفوف", "بامية"]],
  ["broccoli", ["broccoli", "cauliflower", "بروكلي", "قرنبيط"]],
  ["mushroom", ["mushroom", "فطر", "مشروم"]],
  ["ear-of-corn", ["corn", "ذرة"]],
  ["avocado", ["avocado", "أفوكادو"]],
  ["olive", ["olive", "oil", "زيتون", "زيت"]],
  ["herb", ["parsley", "cilantro", "coriander", "mint", "basil", "thyme", "dill", "herb", "بقدونس", "كزبرة", "نعناع", "ريحان", "زعتر", "شبت"]],
  ["ginger-root", ["ginger", "turmeric", "زنجبيل", "كركم"]],
  ["shrimp", ["shrimp", "prawn", "روبيان", "جمبري"]],
  ["fish", ["fish", "salmon", "tuna", "hammour", "سمك", "سلمون", "تونة", "هامور"]],
  ["poultry-leg", ["chicken", "poultry", "turkey", "دجاج", "فراخ", "ديك"]],
  ["cut-of-meat", ["beef", "lamb", "meat", "steak", "mutton", "veal", "liver", "لحم", "ضأن", "غنم", "خروف", "كبد"]],
  ["egg", ["egg", "بيض"]],
  ["butter", ["butter", "ghee", "زبد", "سمن"]],
  ["cheese-wedge", ["cheese", "parmesan", "mozzarella", "feta", "halloumi", "جبن", "حلوم"]],
  ["glass-of-milk", ["milk", "cream", "yogurt", "yoghurt", "laban", "حليب", "قشطة", "كريمة", "زبادي", "لبن"]],
  ["cooked-rice", ["rice", "أرز", "رز"]],
  ["spaghetti", ["pasta", "spaghetti", "noodle", "macaroni", "معكرونة", "باستا", "سباغيتي", "شعيرية"]],
  ["bread", ["bread", "flour", "pita", "toast", "tortilla", "dough", "خبز", "طحين", "دقيق", "تورتيلا", "عجين"]],
  ["beans", ["bean", "lentil", "chickpea", "hummus", "فاصوليا", "عدس", "حمص", "فول"]],
  ["chestnut", ["almond", "cashew", "walnut", "pistachio", "nut", "لوز", "كاجو", "جوز", "فستق", "مكسرات"]],
  ["honey-pot", ["honey", "syrup", "molasses", "عسل", "دبس"]],
  ["candy", ["sugar", "سكر"]],
  ["salt", ["salt", "pepper", "spice", "cumin", "cinnamon", "cardamom", "saffron", "seasoning", "ملح", "فلفل", "بهار", "كمون", "قرفة", "هيل", "زعفران"]],
  ["palm-tree", ["date", "تمر"]],
  ["grapes", ["grape", "raisin", "عنب", "زبيب"]],
  ["red-apple", ["apple", "تفاح"]],
  ["banana", ["banana", "موز"]],
  ["chocolate-bar", ["chocolate", "cocoa", "شوكولا", "كاكاو"]],
  ["canned-food", ["sauce", "mayo", "ketchup", "paste", "صلصة", "صوص", "مايونيز", "كاتشب", "معجون"]],
  ["droplet", ["water", "stock", "broth", "ماء", "مرق"]],
];

export const DEFAULT_FOOD_GLYPH: GlyphName = "spoon";

export function getFoodGlyph(name: string | null | undefined): GlyphName {
  const normalized = (name ?? "").trim().toLowerCase();
  if (!normalized) return DEFAULT_FOOD_GLYPH;

  for (const [glyph, keywords] of FOOD_GLYPHS) {
    if (keywords.some((keyword) => normalized.includes(keyword))) return glyph;
  }

  return DEFAULT_FOOD_GLYPH;
}
